### ISSUE TITLE
App crashes after clicking on "Sign in With Google" button

### ISSUE THREAD

**Issue by tmtben** [AseemWangoo/hands_on_kotlin#5]
Hello,
I would like to run your app.
At app startup I can see "periodic backing" notification (txt file is created).
When I click on "Sign in With Google" button, the app crashes, please find below the log trace.
Best regards,
Ben

```
2021-09-23 16:52:24.607 15128-15128/com.aseemwangoo.handsonkotlin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aseemwangoo.handsonkotlin, PID: 15128
    java.lang.IllegalArgumentException: Given String is empty or null
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.5.0:5)
        at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.zaa(com.google.android.gms:play-services-base@@17.5.0:56)
        at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.requestIdToken(com.google.android.gms:play-services-base@@17.5.0:29)
        at com.aseemwangoo.handsonkotlin.google.GoogleApiContract.createIntent(GoogleApiContract.kt:16)
        at com.aseemwangoo.handsonkotlin.google.GoogleApiContract.createIntent(GoogleApiContract.kt:13)
        at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:166)
        at androidx.activity.result.ActivityResultRegistry$3.launch(ActivityResultRegistry.java:224)
        at androidx.activity.compose.ActivityResultLauncherHolder.launch(ActivityResultRegistry.kt:159)
        at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$returnedLauncher$1$1.launch(ActivityResultRegistry.kt:130)
        at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
        at com.aseemwangoo.handsonkotlin.screens.AuthScreenKt$AuthScreen$1.invoke(AuthScreen.kt:60)
        at com.aseemwangoo.handsonkotlin.screens.AuthScreenKt$AuthScreen$1.invoke(AuthScreen.kt:60)
        at com.aseemwangoo.handsonkotlin.screens.AuthScreenKt$AuthView$1$1$1.invoke(AuthScreen.kt:97)
        at com.aseemwangoo.handsonkotlin.screens.AuthScreenKt$AuthView$1$1$1.invoke(AuthScreen.kt:95)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:130)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:130)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:376)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:369)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:403)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:395)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:300)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:422)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:319)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:332)
        at androidx.compose.ui.input.pointer.Node.dispatchToPointerInputFilter(HitPathTracker.kt:361)
        at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:309)
        at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:305)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchChanges(HitPathTracker.kt:180)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:112)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:80)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:748)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
2021-09-23 16:52:24.608 15128-15128/com.aseemwangoo.handsonkotlin E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1873)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
        at android.view.View.dispatchPointerEvent(View.java:14568)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6022)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5825)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8086)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8037)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7998)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8209)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by AseemWangoo** [comment]
Hello Ben,

Seeing the first line of the error message
   " java.lang.IllegalArgumentException: Given String is empty or null "

This means the string value is empty for 
![image](https://user-images.githubusercontent.com/16626254/134611684-390cb999-8f1a-4330-953c-9d841d0e7e13.png)

https://github.com/AseemWangoo/hands_on_kotlin/blob/master/app/src/main/res/values/strings.xml

Please find the video tutorial here https://www.youtube.com/watch?v=fqVqq8dqTTo

to see how to get the value

**Comment by tmtben** [comment]
Thanks Aseem.
I notice the string "google_cloud_server_client_id" is waiting for the "web client" id and not the "android client" one.
Now I can run your app :-)

Your source code is a very good example for me. Many thanks for sharing your work!

Best regards,
Ben
